### ISSUE TITLE
mnemonic() and op_str() return empty strings

### ISSUE THREAD

**Issue by osa1** [capstone-rust/capstone-rs#6]
I realized it returns empty strings for all the instructions. I then tried to run the tests and indeed they fail because of the same error:

```
     Running target/debug/capstone-60f7fa6151b4be09

running 3 tests
test test::test_invalid_mode ... ok
test test::test_x86_simple ... FAILED
test test::test_x86_names ... FAILED

failures:

---- test::test_x86_simple stdout ----
        thread 'test::test_x86_simple' panicked at 'assertion failed: `(left == right)` (left: `""`, right: `"push"`)', src/lib.rs:36

---- test::test_x86_names stdout ----
        thread 'test::test_x86_names' panicked at 'Couldn't get register name', src/lib.rs:60
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    test::test_x86_names
    test::test_x86_simple

test result: FAILED. 1 passed; 2 failed; 0 ignored; 0 measured

error: test failed
```

**Comment by osa1** [comment]
Demo program also doesn't print the mnemonics:

```
➜  capstone-rs git:(master) cargo run --example=demo
     Running `target/debug/examples/demo`
Got 2 instructions
0x1000:  
0x1001:  
```

**Comment by richo** [comment]
What version of capstone are you linking against?

**Comment by tmfink** [comment]
Closing due to lack of response.
